name: Sync to master

on:
  push:
    branches:
      - "source"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Chekcout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Push to master
      run: |
        git checkout master
        git rebase source
        git push -f master || true
